language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
before_script:
  - mysql -e 'create database enju_test'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_ndl.gemfile
  - gemfiles/rails_4.2_nii.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
matrix:
  exclude:
  - gemfile: gemfiles/rails_4.2_ndl.gemfile
  - gemfile: gemfiles/rails_4.2_nii.gemfile
  - rvm: 1.9.3
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 1.9.3
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_4.2.gemfile
  - rvm: 2.1.8
    gemfile: gemfiles/rails_3.2.gemfile
  - rvm: 2.2.4
    gemfile: gemfiles/rails_3.2.gemfile
  include:
  - gemfile: gemfiles/rails_4.2_ndl.gemfile
    rvm: 2.2.4
    env: DB=postgresql
  - gemfile: gemfiles/rails_4.2_nii.gemfile
    rvm: 2.2.4
    env: DB=postgresql
notifications:
  slack:
    secure: rsdAy+UmEvL1DU2TIAS27NjH9MVH0xuyWyoX59MIfRaeCm9AtirT6ZyZMhfljE9w+r8m9KGrFVGp/oNAXevjLdzvxin2R4VjEeBtK2PEBQA7EoAnJuHY8UvrE/t4TflM96ChnmaYSRx9aawRN9j5QqwIGMPOoG3KqVEDLW2uNq0=
sudo: false
