language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
before_script:
  - psql -c 'create database enju_loc_dummy_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake app:sunspot:solr:start
services:
  - redis-server
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.2_ndl.gemfile
  - gemfiles/rails_5.2_nii.gemfile
env:
  - DB=postgresql
notifications:
  slack:
    secure: rsdAy+UmEvL1DU2TIAS27NjH9MVH0xuyWyoX59MIfRaeCm9AtirT6ZyZMhfljE9w+r8m9KGrFVGp/oNAXevjLdzvxin2R4VjEeBtK2PEBQA7EoAnJuHY8UvrE/t4TflM96ChnmaYSRx9aawRN9j5QqwIGMPOoG3KqVEDLW2uNq0=
sudo: false
