language: ruby
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
before_script:
  - mysql -e 'create database enju_test DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - psql -c 'create database enju_test;' -U postgres
  - bundle exec rake db:migrate
services:
  - redis-server
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.2_ndl.gemfile
  - gemfiles/rails_4.2_nii.gemfile
  - gemfiles/rails_5.0.gemfile
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
matrix:
  exclude:
  allow_failures:
    - gemfile: gemfiles/rails_5.0.gemfile
notifications:
  slack:
    secure: rsdAy+UmEvL1DU2TIAS27NjH9MVH0xuyWyoX59MIfRaeCm9AtirT6ZyZMhfljE9w+r8m9KGrFVGp/oNAXevjLdzvxin2R4VjEeBtK2PEBQA7EoAnJuHY8UvrE/t4TflM96ChnmaYSRx9aawRN9j5QqwIGMPOoG3KqVEDLW2uNq0=
sudo: false
